from openai import OpenAI, RateLimitError
from private_keys import OPENROUTER_KEY

class OpenRouterDeepSeek:

    def __init__(self):
        self.client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=OPENROUTER_KEY,
        )

    def send_prompt(self, prompt):
        systemMessage="""You can receive messages in English or Romanian, but your response must always be in English."
                      "The given prompt will represent an object/scene that is going to be generated by Shap-E."
                      "Create a more detailed and precise description so that Shap-E can generate the object much more accurately."
                      "Do not add any other details or messages in the response, only the description of the object."""
        try:
            completion=self.client.chat.completions.create(
                  extra_headers={},
                  extra_body={},
                  model="deepseek/deepseek-chat-v3-0324:free",
                  messages=[
                    {"role": "system","content": systemMessage},
                    {"role": "user","content": prompt}
                  ]
                )
        except RateLimitError as e:
            print("Rate limit exceeded. Please retry later.")
            print(e)
            return -1
        except Exception as e:
            print("Other error:", e)
            return -1
        return completion.choices[0].message.content